etl_db:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: postgres
      password: "{{ env_var('DBT_POSTGRES_PASSWORD') }}"
      dbname: etl_db
      schema: prep
      threads: 2
      keepalives_idle: 0
      connect_timeout: 10

    
    prod:
      type: postgres
      host: localhost
      port: 5432
      user: postgres
      password: "{{ env_var('DBT_POSTGRES_PASSWORD') }}"
      dbname: etl_db
      schema: prep
      threads: 2
