# ============================================================================
# Profiles dbt - Configuration PostgreSQL
# ============================================================================
# Fichier : dbt/etl_db/profiles.yml
# ============================================================================

etl_db:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: postgres
      password: "{{ env_var('DBT_POSTGRES_PASSWORD') | b64decode }}"
      dbname: etl_db
      schema: raw
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
      search_path: raw,staging,ods,marts,public
      client_encoding: UTF8
    
    prod:
      type: postgres
      host: localhost
      port: 5432
      user: postgres
      password: "{{ env_var('DBT_POSTGRES_PASSWORD') | b64decode }}"
      dbname: etl_db
      schema: ods
      threads: 8
      search_path: ods,marts,raw,staging,public
      client_encoding: UTF8