{{ config(materialized='view') }}

-- Staging model for lisval

SELECT
    "cle_courante" AS cle_courante,
    "cle_pere" AS cle_pere,
    "cod_autre" AS cod_autre,
    "cod_tiers" AS cod_tiers,
    "flag_repli" AS flag_repli,
    "index_c" AS index_c,
    "index_d" AS index_d,
    "index_e" AS index_e,
    "index_l" AS index_l,
    "index_n" AS index_n,
    "index_t" AS index_t,
    "liste" AS liste,
    "no_ordre" AS no_ordre,
    "TabPart_lisval" AS tabpart_lisval,
    "typ_fich" AS typ_fich,
    "uniq_id" AS uniq_id,
    "za0" AS za0,
    "za1" AS za1,
    "za2" AS za2,
    "za3" AS za3,
    "za4" AS za4,
    "za5" AS za5,
    "za6" AS za6,
    "za7" AS za7,
    "za8" AS za8,
    "za9" AS za9,
    "zc0" AS zc0,
    "zd0" AS zd0,
    "zd1" AS zd1,
    "zd2" AS zd2,
    "zd3" AS zd3,
    "zd4" AS zd4,
    "zd5" AS zd5,
    "zd6" AS zd6,
    "zd7" AS zd7,
    "zd8" AS zd8,
    "zd9" AS zd9,
    "ze0" AS ze0,
    "ze1" AS ze1,
    "ze2" AS ze2,
    "ze3" AS ze3,
    "ze4" AS ze4,
    "ze5" AS ze5,
    "ze6" AS ze6,
    "ze7" AS ze7,
    "ze8" AS ze8,
    "ze9" AS ze9,
    "zl0" AS zl0,
    "zl1" AS zl1,
    "zl2" AS zl2,
    "zl3" AS zl3,
    "zl4" AS zl4,
    "zl5" AS zl5,
    "zl6" AS zl6,
    "zl7" AS zl7,
    "zl8" AS zl8,
    "zl9" AS zl9,
    "zn0" AS zn0,
    "zn1" AS zn1,
    "zn2" AS zn2,
    "zn3" AS zn3,
    "zn4" AS zn4,
    "zn5" AS zn5,
    "zn6" AS zn6,
    "zn7" AS zn7,
    "zn8" AS zn8,
    "zn9" AS zn9,
    "zt0" AS zt0,
    "zt1" AS zt1,
    "zt2" AS zt2,
    "zt3" AS zt3,
    "zt4" AS zt4,
    "zt5" AS zt5,
    "zt6" AS zt6,
    "zt7" AS zt7,
    "zt8" AS zt8,
    "zt9" AS zt9,
    _loaded_at,
    _source_file,
    _sftp_log_id
FROM {{ source('ods', 'lisval') }}
