{{ config(materialized='view') }}

-- Staging model for stock

SELECT
    "arr_sit" AS arr_sit,
    "cod_pro" AS cod_pro,
    "coef_dep" AS coef_dep,
    "cum_ent" AS cum_ent,
    "cum_sor" AS cum_sor,
    "dat_cal" AS dat_cal,
    "dat_ent" AS dat_ent,
    "dat_sor" AS dat_sor,
    "depot" AS depot,
    "detrompeur" AS detrompeur,
    "emplac" AS emplac,
    "flag_repli" AS flag_repli,
    "fut_stock" AS fut_stock,
    "hr_ent" AS hr_ent,
    "hr_sor" AS hr_sor,
    "magasin" AS magasin,
    "maxi" AS maxi,
    "mini" AS mini,
    "nb_mvt" AS nb_mvt,
    "pmp" AS pmp,
    "pmp_sit" AS pmp_sit,
    "poi_net_sit" AS poi_net_sit,
    "poi_sit" AS poi_sit,
    "poids" AS poids,
    "poids_net" AS poids_net,
    "px_rvt" AS px_rvt,
    "px_sim" AS px_sim,
    "px_std" AS px_std,
    "px_std2" AS px_std2,
    "px_std3" AS px_std3,
    "qte_sit" AS qte_sit,
    "s_alerte" AS s_alerte,
    "s_pt_cde" AS s_pt_cde,
    "s_secu" AS s_secu,
    "stk_maxi" AS stk_maxi,
    "stk_mini" AS stk_mini,
    "stock" AS stock,
    "TabPart_stock" AS tabpart_stock,
    "val_ent" AS val_ent,
    "val_sor" AS val_sor,
    "vpm" AS vpm,
    "vpr" AS vpr,
    _loaded_at,
    _source_file,
    _sftp_log_id
FROM {{ source('ods', 'stock') }}
