{{ config(materialized='view') }}

/*
    ============================================================================
    Modèle PREP : entetcli
    ============================================================================
    Généré automatiquement le 2025-12-05 15:23:43
    
    Source       : ods.entetcli
    Lignes       : 12,400
    Colonnes ODS : 463
    Colonnes PREP: 129
    Exclues      : 334 (72.1%)
    
    Exclusions:
      - Techniques ETL  : 7
      - 100% NULL       : 213
      - Constantes      : 107
      - Faible valeur   : 7
    ============================================================================
*/

SELECT
    "cod_cli" AS cod_cli,
    "no_cde" AS no_cde,
    "no_bl" AS no_bl,
    "achev" AS achev,
    "dat_cde" AS dat_cde,
    "dat_px" AS dat_px,
    "qui" AS qui,
    "ref_cde" AS ref_cde,
    "not_ref" AS not_ref,
    "dat_liv" AS dat_liv,
    "dat_livd" AS dat_livd,
    "dat_dep" AS dat_dep,
    "depot" AS depot,
    "civ_fac" AS civ_fac,
    "k_postf" AS k_postf,
    "villef" AS villef,
    "paysf" AS paysf,
    "chif_bl" AS chif_bl,
    "proforma" AS proforma,
    "liasse" AS liasse,
    "num_tel" AS num_tel,
    "num_fax" AS num_fax,
    "civ_liv" AS civ_liv,
    "k_postl" AS k_postl,
    "villel" AS villel,
    "paysl" AS paysl,
    "devise" AS devise,
    "tx_ech_d" AS tx_ech_d,
    "iden_ce" AS iden_ce,
    "code_reg" AS code_reg,
    "code_ech" AS code_ech,
    "nb_ech" AS nb_ech,
    "langue" AS langue,
    "regime" AS regime,
    "type_fac" AS type_fac,
    "fac_dvs" AS fac_dvs,
    "fac_pxa" AS fac_pxa,
    "edt_arc" AS edt_arc,
    "cl_grp" AS cl_grp,
    "cl_fact" AS cl_fact,
    "cl_paye" AS cl_paye,
    "tarif" AS tarif,
    "region" AS region,
    "famille" AS famille,
    "cat_tar" AS cat_tar,
    "no_tarif" AS no_tarif,
    "borne" AS borne,
    "relk_bp" AS relk_bp,
    "der_bp" AS der_bp,
    "nb_bp" AS nb_bp,
    "mnt_rlk" AS mnt_rlk,
    "bl_sai" AS bl_sai,
    "poids" AS poids,
    "mod_liv" AS mod_liv,
    "colis" AS colis,
    "zon_geo" AS zon_geo,
    "transpor" AS transpor,
    "mt_cde" AS mt_cde,
    "no_fact" AS no_fact,
    "fac_edi" AS fac_edi,
    "fac_maj" AS fac_maj,
    "usr_crt" AS usr_crt,
    "dat_crt" AS dat_crt,
    "usr_mod" AS usr_mod,
    "dat_mod" AS dat_mod,
    "edt_bp" AS edt_bp,
    "edt_bl" AS edt_bl,
    "edt_fac" AS edt_fac,
    "maj_ach" AS maj_ach,
    "blocage" AS blocage,
    "ori_cde" AS ori_cde,
    "qui_liv" AS qui_liv,
    "palette" AS palette,
    "informat" AS informat,
    "typ_con" AS typ_con,
    "dat_dev" AS dat_dev,
    "no_devis" AS no_devis,
    "mt_fact" AS mt_fact,
    "comment" AS comment,
    "mt_ht" AS mt_ht,
    "hr_sai" AS hr_sai,
    "bl_ori" AS bl_ori,
    "edi_rlv" AS edi_rlv,
    "motif_av" AS motif_av,
    "k_post2f" AS k_post2f,
    "k_post2l" AS k_post2l,
    "volume" AS volume,
    "no_info" AS no_info,
    "sta_pce" AS sta_pce,
    "semaine" AS semaine,
    "dat_mad" AS dat_mad,
    "ind_bp" AS ind_bp,
    "mt_fach" AS mt_fach,
    "bp_ini" AS bp_ini,
    "mt_ini" AS mt_ini,
    "inc_deb" AS inc_deb,
    "trs_deb" AS trs_deb,
    "adrfac4" AS adrfac4,
    "adrliv4" AS adrliv4,
    "hr_bp" AS hr_bp,
    "dat_bp" AS dat_bp,
    "pce_a" AS pce_a,
    "ndos" AS ndos,
    "cpt_bq" AS cpt_bq,
    "hr_bl" AS hr_bl,
    "dat_bl" AS dat_bl,
    "dat_acc" AS dat_acc,
    "dat_rll" AS dat_rll,
    "liv_cpl" AS liv_cpl,
    "temps" AS temps,
    "arc_mail" AS arc_mail,
    "civ_cde" AS civ_cde,
    "villec" AS villec,
    "paysc" AS paysc,
    "k_post2c" AS k_post2c,
    "typ_elem" AS typ_elem,
    "cat_cum" AS cat_cum,
    "dat_vald" AS dat_vald,
    "cde_ini" AS cde_ini,
    "poi_ini" AS poi_ini,
    "cod_site" AS cod_site,
    "s2_famille" AS s2_famille,
    "uniq_id" AS uniq_id,
    "metre_lin" AS metre_lin,
    "lias_bl" AS lias_bl,
    "pal_sol" AS pal_sol,
    "edt_cde" AS edt_cde,
    "edt_dev" AS edt_dev,
    "_etl_run_id" AS _etl_run_id
FROM {{ source('ods', 'entetcli') }}
