{{ config(materialized='view') }}

/*
    Modèle PREP pour crn
    Généré automatiquement depuis ODS pour inclure les colonnes éclataées (Extent)
*/

SELECT
    "cod_crn" AS cod_crn,
    "nom_crn" AS nom_crn,
    "ville" AS ville,
    "form_jur" AS form_jur,
    "capital" AS capital,
    "usr_crt" AS usr_crt,
    "dat_crt" AS dat_crt,
    "usr_mod" AS usr_mod,
    "dat_mod" AS dat_mod,
    "zal_1" AS zal_1,
    "zal_2" AS zal_2,
    "zal_3" AS zal_3,
    "zal_4" AS zal_4,
    "zal_5" AS zal_5,
    "znu_1" AS znu_1,
    "znu_2" AS znu_2,
    "znu_3" AS znu_3,
    "znu_4" AS znu_4,
    "znu_5" AS znu_5,
    "zta_1" AS zta_1,
    "zta_2" AS zta_2,
    "zta_3" AS zta_3,
    "zta_4" AS zta_4,
    "zta_5" AS zta_5,
    "zda_1" AS zda_1,
    "zda_2" AS zda_2,
    "zda_3" AS zda_3,
    "zda_4" AS zda_4,
    "zda_5" AS zda_5,
    "pays" AS pays,
    "internet" AS internet,
    "zlo_1" AS zlo_1,
    "zlo_2" AS zlo_2,
    "zlo_3" AS zlo_3,
    "zlo_4" AS zlo_4,
    "zlo_5" AS zlo_5,
    "k_post2" AS k_post2,
    "effectif" AS effectif,
    "ca_crn" AS ca_crn,
    "civilite" AS civilite,
    "adresse_1" AS adresse_1,
    "adresse_2" AS adresse_2,
    "num_tel" AS num_tel,
    "num_fax" AS num_fax,
    "adresse4" AS adresse4,
    "no_info" AS no_info,
    "texte" AS texte,
    "part" AS part,
    "famille" AS famille,
    "type" AS type,
    "TabPart_crn" AS tabpart_crn,
    "flag_repli" AS flag_repli,
    "adresse5" AS adresse5,
    "_etl_loaded_at" AS _etl_loaded_at,
    "_etl_updated_at" AS _etl_updated_at,
    "_etl_run_id" AS _etl_run_id,
    "_etl_source" AS _etl_source,
    "_etl_hashdiff" AS _etl_hashdiff,
    "_etl_is_active" AS _etl_is_active,
    "_etl_valid_from" AS _etl_valid_from,
    "_etl_valid_to" AS _etl_valid_to
FROM {{ source('ods', 'crn') }}
