{{ config(materialized='view') }}

-- Staging model for soumission

SELECT
    "achev" AS achev,
    "cat_tar" AS cat_tar,
    "cod_dec1" AS cod_dec1,
    "cod_dec2" AS cod_dec2,
    "cod_dec3" AS cod_dec3,
    "cod_dec4" AS cod_dec4,
    "cod_dec5" AS cod_dec5,
    "cod_pro" AS cod_pro,
    "cod_tiers" AS cod_tiers,
    "continental" AS continental,
    "dat_deb" AS dat_deb,
    "dat_fin" AS dat_fin,
    "dat_liv" AS dat_liv,
    "depot" AS depot,
    "en-tete" AS en_tete,
    "eve_exc" AS eve_exc,
    "exclusif" AS exclusif,
    "f_cl" AS f_cl,
    "flag_repli" AS flag_repli,
    "grille_rem" AS grille_rem,
    "groupement" AS groupement,
    "lib_contrat" AS lib_contrat,
    "lien_ach" AS lien_ach,
    "M_dat" AS m_dat,
    "m_qte" AS m_qte,
    "m_qui" AS m_qui,
    "md5" AS md5,
    "national" AS national,
    "no_cde" AS no_cde,
    "no_contrat" AS no_contrat,
    "no_lot" AS no_lot,
    "non_rfa" AS non_rfa,
    "ope_exc" AS ope_exc,
    "ord_rem" AS ord_rem,
    "pere" AS pere,
    "principal" AS principal,
    "px_net" AS px_net,
    "qte" AS qte,
    "qte_his" AS qte_his,
    "region_depots" AS region_depots,
    "regional" AS regional,
    "rem_app" AS rem_app,
    "remise1" AS remise1,
    "remise2" AS remise2,
    "remise3" AS remise3,
    "remise4" AS remise4,
    "statut" AS statut,
    "TabPart_soumission" AS tabpart_soumission,
    "typ_con" AS typ_con,
    "typ_rem1" AS typ_rem1,
    "typ_rem2" AS typ_rem2,
    "typ_rem3" AS typ_rem3,
    "typ_rem4" AS typ_rem4,
    "uniq_id" AS uniq_id,
    "vente" AS vente,
    "zal" AS zal,
    "zda" AS zda,
    "zlo" AS zlo,
    "znu" AS znu,
    "zta" AS zta,
    _loaded_at,
    _source_file,
    _sftp_log_id
FROM {{ source('ods', 'soumission') }}
