{{ config(materialized='view') }}

-- Staging model for clcondi

SELECT
    "applic" AS applic,
    "aut_tar" AS aut_tar,
    "c_promo" AS c_promo,
    "canal" AS canal,
    "cat_tar" AS cat_tar,
    "chg_tarif" AS chg_tarif,
    "chx_promo" AS chx_promo,
    "cod_cli" AS cod_cli,
    "cod_dec" AS cod_dec,
    "cod_dec1" AS cod_dec1,
    "cod_dec2" AS cod_dec2,
    "cod_dec3" AS cod_dec3,
    "cod_dec4" AS cod_dec4,
    "cod_dec5" AS cod_dec5,
    "cod_fou" AS cod_fou,
    "cod_pro" AS cod_pro,
    "coef_av" AS coef_av,
    "coef_rq" AS coef_rq,
    "cou_fix" AS cou_fix,
    "dat_crt" AS dat_crt,
    "dat_deb" AS dat_deb,
    "dat_fin" AS dat_fin,
    "dat_mod" AS dat_mod,
    "depot" AS depot,
    "eve_exc" AS eve_exc,
    "exc_cli" AS exc_cli,
    "exc_pro" AS exc_pro,
    "f_cl" AS f_cl,
    "fam_tar" AS fam_tar,
    "flag_repli" AS flag_repli,
    "gratuit" AS gratuit,
    "grille_rem" AS grille_rem,
    "intitule" AS intitule,
    "no_cond" AS no_cond,
    "no_tarif" AS no_tarif,
    "non_rfa" AS non_rfa,
    "ope_exc" AS ope_exc,
    "ord_rem" AS ord_rem,
    "promo" AS promo,
    "pvc" AS pvc,
    "px_brut" AS px_brut,
    "px_cli" AS px_cli,
    "px_net" AS px_net,
    "px_poi" AS px_poi,
    "px_vte" AS px_vte,
    "qte" AS qte,
    "qte_rq" AS qte_rq,
    "rayon" AS rayon,
    "rem_app" AS rem_app,
    "rem_trs" AS rem_trs,
    "remise1" AS remise1,
    "remise2" AS remise2,
    "remise3" AS remise3,
    "remise4" AS remise4,
    "s2_cat" AS s2_cat,
    "s3_cat" AS s3_cat,
    "s3_tar" AS s3_tar,
    "s4_cat" AS s4_cat,
    "s4_tar" AS s4_tar,
    "sf_tar" AS sf_tar,
    "TabPart_clcondi" AS tabpart_clcondi,
    "typ_gra" AS typ_gra,
    "typ_gsd" AS typ_gsd,
    "typ_rem1" AS typ_rem1,
    "typ_rem2" AS typ_rem2,
    "typ_rem3" AS typ_rem3,
    "typ_rem4" AS typ_rem4,
    "uniq_id" AS uniq_id,
    "usr_crt" AS usr_crt,
    "usr_mod" AS usr_mod,
    "zon_lib" AS zon_lib,
    _loaded_at,
    _source_file,
    _sftp_log_id
FROM {{ source('ods', 'clcondi') }}
