{{ config(materialized='view') }}

-- Staging model for focondi

SELECT
    "c_promo" AS c_promo,
    "cod_dec1" AS cod_dec1,
    "cod_dec2" AS cod_dec2,
    "cod_dec3" AS cod_dec3,
    "cod_dec4" AS cod_dec4,
    "cod_dec5" AS cod_dec5,
    "cod_fou" AS cod_fou,
    "cod_pro" AS cod_pro,
    "coef_ach" AS coef_ach,
    "coef_vte" AS coef_vte,
    "condi_a" AS condi_a,
    "condi_v" AS condi_v,
    "dat_crt" AS dat_crt,
    "dat_deb" AS dat_deb,
    "dat_fin" AS dat_fin,
    "dat_mod" AS dat_mod,
    "depot" AS depot,
    "derog_fou" AS derog_fou,
    "fam_tar" AS fam_tar,
    "flag_repli" AS flag_repli,
    "gratuit" AS gratuit,
    "grille_rem" AS grille_rem,
    "no_cond" AS no_cond,
    "ord_rem" AS ord_rem,
    "promo" AS promo,
    "px_ach" AS px_ach,
    "px_refa" AS px_refa,
    "px_refv" AS px_refv,
    "qte" AS qte,
    "qte_rq" AS qte_rq,
    "rem_app" AS rem_app,
    "remise1" AS remise1,
    "remise2" AS remise2,
    "remise3" AS remise3,
    "remise4" AS remise4,
    "s3_tar" AS s3_tar,
    "s4_tar" AS s4_tar,
    "sf_tar" AS sf_tar,
    "TabPart_focondi" AS tabpart_focondi,
    "typ_gra" AS typ_gra,
    "typ_gsd" AS typ_gsd,
    "typ_rem1" AS typ_rem1,
    "typ_rem2" AS typ_rem2,
    "typ_rem3" AS typ_rem3,
    "typ_rem4" AS typ_rem4,
    "usr_crt" AS usr_crt,
    "usr_mod" AS usr_mod,
    _loaded_at,
    _source_file,
    _sftp_log_id
FROM {{ source('raw', 'raw_focondi') }}
