version: 2

sources:
  - name: ods
    description: "Tables ODS créées par le pipeline Python (UPSERT avec hashdiff)"
    database: etl_db
    schema: ods
    tables:
      - name: clcondi
      - name: client
      - name: crn
      - name: crnar
      - name: deppro
      - name: entetcli
      - name: entetfou
      - name: focondi
      - name: fournis
      - name: hisprixa
      - name: hisprixv
      - name: histoent
      - name: histolig
      - name: lignecli
      - name: lignefou
      - name: lisval
      - name: lldespro
      - name: prmultfo
      - name: prnomenc
      - name: produit
      - name: prprixv
      - name: soumission
      - name: stock
      - name: tabgco
      - name: typelem