{{ config(materialized='view') }}

/*
    ============================================================================
    Modèle PREP : histolig
    ============================================================================
    Généré automatiquement le 2025-12-05 15:30:10
    
    Source       : ods.histolig
    Lignes       : 10,828
    Colonnes ODS : 447
    Colonnes PREP: 133
    Exclues      : 314 (70.2%)
    
    Exclusions:
      - Techniques ETL  : 7
      - 100% NULL       : 160
      - Constantes      : 137
      - Faible valeur   : 10
    ============================================================================
*/

SELECT
    "cod_pro" AS cod_pro,
    "depot" AS depot,
    "dat_mvt" AS dat_mvt,
    "typ_mvt" AS typ_mvt,
    "ref_mvt" AS ref_mvt,
    "qte_unit" AS qte_unit,
    "px_unit" AS px_unit,
    "sous_type" AS sous_type,
    "typ_elem" AS typ_elem,
    "cod_cf" AS cod_cf,
    "no_cde" AS no_cde,
    "no_bl" AS no_bl,
    "div_fac" AS div_fac,
    "no_ligne" AS no_ligne,
    "nom_pro" AS nom_pro,
    "qte" AS qte,
    "px_vte" AS px_vte,
    "remise1" AS remise1,
    "rem_app" AS rem_app,
    "refint" AS refint,
    "groupe" AS groupe,
    "famille" AS famille,
    "s_famille" AS s_famille,
    "fam_cpt" AS fam_cpt,
    "lib_univ" AS lib_univ,
    "lib_conv" AS lib_conv,
    "conv_px" AS conv_px,
    "cod_fou" AS cod_fou,
    "refext" AS refext,
    "devise" AS devise,
    "px_ach" AS px_ach,
    "lib_unia" AS lib_unia,
    "lib_cona" AS lib_cona,
    "fam_tar" AS fam_tar,
    "code_tva" AS code_tva,
    "enc_db" AS enc_db,
    "calcul" AS calcul,
    "px_refv" AS px_refv,
    "px_refa" AS px_refa,
    "px_ach_d" AS px_ach_d,
    "pmp" AS pmp,
    "gratuit" AS gratuit,
    "forcer" AS forcer,
    "dat_liv" AS dat_liv,
    "total" AS total,
    "tot_txt" AS tot_txt,
    "typ_pha" AS typ_pha,
    "conv_sto" AS conv_sto,
    "px_vte_i" AS px_vte_i,
    "dev_vte" AS dev_vte,
    "lien_nmc" AS lien_nmc,
    "maj_stk" AS maj_stk,
    "edt_nmc" AS edt_nmc,
    "conv_md" AS conv_md,
    "qte_cde" AS qte_cde,
    "n_surlig" AS n_surlig,
    "calc_uv" AS calc_uv,
    "qte_uc" AS qte_uc,
    "px_rvt" AS px_rvt,
    "coef_dep" AS coef_dep,
    "poid_tot" AS poid_tot,
    "maj_stat" AS maj_stat,
    "sf_tar" AS sf_tar,
    "qui" AS qui,
    "mt_ht" AS mt_ht,
    "lien_con" AS lien_con,
    "master" AS master,
    "ord_nmc" AS ord_nmc,
    "garantie" AS garantie,
    "cde_cf" AS cde_cf,
    "lig_fou" AS lig_fou,
    "volume" AS volume,
    "num_ave" AS num_ave,
    "dafaca" AS dafaca,
    "dat_mad" AS dat_mad,
    "no_bl_a" AS no_bl_a,
    "lien_emp" AS lien_emp,
    "reg_deb" AS reg_deb,
    "no_contrat" AS no_contrat,
    "type_prix" AS type_prix,
    "hr_vp" AS hr_vp,
    "dat_vp" AS dat_vp,
    "qui_p" AS qui_p,
    "ind_con" AS ind_con,
    "lig_con" AS lig_con,
    "ndos" AS ndos,
    "s3_tar" AS s3_tar,
    "s4_tar" AS s4_tar,
    "reg_fact" AS reg_fact,
    "typ_gra" AS typ_gra,
    "nb_ua" AS nb_ua,
    "nb_uv" AS nb_uv,
    "pp_ua" AS pp_ua,
    "dat_acc" AS dat_acc,
    "dat_rll" AS dat_rll,
    "lien_frais" AS lien_frais,
    "poid_net" AS poid_net,
    "s3_famille" AS s3_famille,
    "s4_famille" AS s4_famille,
    "qui_v" AS qui_v,
    "nom_pr2" AS nom_pr2,
    "no_lot" AS no_lot,
    "mt_ttc" AS mt_ttc,
    "no_unique" AS no_unique,
    "mt_trsc" AS mt_trsc,
    "ach_ctr" AS ach_ctr,
    "usr_crt" AS usr_crt,
    "dat_crt" AS dat_crt,
    "usr_mod" AS usr_mod,
    "dat_mod" AS dat_mod,
    "consigne" AS consigne,
    "det_frais" AS det_frais,
    "gen_csg" AS gen_csg,
    "hr_mod" AS hr_mod,
    "no_tarif" AS no_tarif,
    "hr_crt" AS hr_crt,
    "uniq_id" AS uniq_id,
    "no_devis" AS no_devis,
    "mt_pa" AS mt_pa,
    "mt_pr" AS mt_pr,
    "mt_pm" AS mt_pm,
    "MScod_fou" AS mscod_fou,
    "MScde_fou" AS mscde_fou,
    "MSlig_fou" AS mslig_fou,
    "pays_ori" AS pays_ori,
    "hr_mvt" AS hr_mvt,
    "qte_ro" AS qte_ro,
    "qte_rc" AS qte_rc,
    "marque" AS marque,
    "no_deb" AS no_deb,
    "lig_deb" AS lig_deb,
    "cod_nom" AS cod_nom,
    "_etl_run_id" AS _etl_run_id
FROM {{ source('ods', 'histolig') }}
