{{ config(materialized='view') }}

/*
    ============================================================================
    Modèle PREP : histoent
    ============================================================================
    Généré automatiquement le 2025-12-05 15:23:57
    
    Source       : ods.histoent
    Lignes       : 19,014
    Colonnes ODS : 455
    Colonnes PREP: 118
    Exclues      : 337 (74.1%)
    
    Exclusions:
      - Techniques ETL  : 7
      - 100% NULL       : 246
      - Constantes      : 78
      - Faible valeur   : 6
    ============================================================================
*/

SELECT
    "cod_cf" AS cod_cf,
    "no_cde" AS no_cde,
    "no_bl" AS no_bl,
    "dat_cde" AS dat_cde,
    "dat_px" AS dat_px,
    "qui" AS qui,
    "ref_cde" AS ref_cde,
    "not_ref" AS not_ref,
    "dat_liv" AS dat_liv,
    "dat_livd" AS dat_livd,
    "dat_dep" AS dat_dep,
    "depot" AS depot,
    "civ_fac" AS civ_fac,
    "villef" AS villef,
    "paysf" AS paysf,
    "chif_bl" AS chif_bl,
    "liasse" AS liasse,
    "num_tel" AS num_tel,
    "num_fax" AS num_fax,
    "civ_liv" AS civ_liv,
    "k_postl" AS k_postl,
    "villel" AS villel,
    "paysl" AS paysl,
    "devise" AS devise,
    "tx_ech_d" AS tx_ech_d,
    "iden_ce" AS iden_ce,
    "code_reg" AS code_reg,
    "code_ech" AS code_ech,
    "langue" AS langue,
    "regime" AS regime,
    "type_fac" AS type_fac,
    "fac_dvs" AS fac_dvs,
    "fac_ttc" AS fac_ttc,
    "fac_pxa" AS fac_pxa,
    "cl_grp" AS cl_grp,
    "cl_fact" AS cl_fact,
    "cl_paye" AS cl_paye,
    "region" AS region,
    "famille" AS famille,
    "cat_tar" AS cat_tar,
    "no_tarif" AS no_tarif,
    "mod_liv" AS mod_liv,
    "colis" AS colis,
    "zon_geo" AS zon_geo,
    "transpor" AS transpor,
    "mt_cde" AS mt_cde,
    "no_fact" AS no_fact,
    "dat_fac" AS dat_fac,
    "usr_crt" AS usr_crt,
    "dat_crt" AS dat_crt,
    "usr_mod" AS usr_mod,
    "dat_mod" AS dat_mod,
    "edt_bl" AS edt_bl,
    "edt_fac" AS edt_fac,
    "qui_liv" AS qui_liv,
    "ori_cde" AS ori_cde,
    "palette" AS palette,
    "no_devis" AS no_devis,
    "hr_sai" AS hr_sai,
    "mt_ht" AS mt_ht,
    "bl_ori" AS bl_ori,
    "mt_fact" AS mt_fact,
    "transit" AS transit,
    "motif_av" AS motif_av,
    "mt_ht_dev" AS mt_ht_dev,
    "no_bl_a" AS no_bl_a,
    "k_post2f" AS k_post2f,
    "k_post2l" AS k_post2l,
    "volume" AS volume,
    "no_info" AS no_info,
    "poids" AS poids,
    "mt_fach" AS mt_fach,
    "bp_ini" AS bp_ini,
    "inc_deb" AS inc_deb,
    "trs_deb" AS trs_deb,
    "adrfac4" AS adrfac4,
    "adrliv4" AS adrliv4,
    "hr_bp" AS hr_bp,
    "dat_bp" AS dat_bp,
    "ndos" AS ndos,
    "cpt_bq" AS cpt_bq,
    "hr_bl" AS hr_bl,
    "dat_bl" AS dat_bl,
    "edi_rlv" AS edi_rlv,
    "dat_acc" AS dat_acc,
    "dat_rll" AS dat_rll,
    "typ_con" AS typ_con,
    "civ_cde" AS civ_cde,
    "villec" AS villec,
    "paysc" AS paysc,
    "k_post2c" AS k_post2c,
    "edi_refcde" AS edi_refcde,
    "typ_elem" AS typ_elem,
    "cat_cum" AS cat_cum,
    "cde_ini" AS cde_ini,
    "pays_e" AS pays_e,
    "typ_fac_edi" AS typ_fac_edi,
    "cod_site" AS cod_site,
    "s2_famille" AS s2_famille,
    "uniq_id" AS uniq_id,
    "hr_mod" AS hr_mod,
    "dat_mad" AS dat_mad,
    "comment" AS comment,
    "metre_lin" AS metre_lin,
    "lias_bl" AS lias_bl,
    "st_interne" AS st_interne,
    "acq_intra" AS acq_intra,
    "pal_sol" AS pal_sol,
    "bon_pay" AS bon_pay,
    "dat_sai" AS dat_sai,
    "edt_cde" AS edt_cde,
    "edt_dev" AS edt_dev,
    "usr_mpce" AS usr_mpce,
    "dat_mpce" AS dat_mpce,
    "usr_his" AS usr_his,
    "dat_his" AS dat_his,
    "hr_his" AS hr_his,
    "_etl_run_id" AS _etl_run_id
FROM {{ source('ods', 'histoent') }}
